sudo: false

language: node_js

before_install:
- '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
- 'npm install -g npm@latest'

script:
- '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm test'

node_js:
  - '0.8'
  - '0.10'
  - '0.11'
  - '0.12'
  - 'iojs-v1.0.0'
  - 'iojs-v2.0.0'
  - 'iojs-v3.0.0'
  - 'iojs'
