sudo: false

language: node_js

notifications:
  email: false

before_install:
  - npm install -g npm@2
  - npm install -g npm

matrix:
  fast_finish: true
  include:
    - node_js: '0.8'
      env: TASK=test
    - node_js: '0.10'
      env: TASK=test
    - node_js: '0.12'
      env: TASK=test
    - node_js: '1'
      env: TASK=test
    - node_js: '2'
      env: TASK=test
    - node_js: '3'
      env: TASK=test
    - node_js: '4'
      env: TASK=test
    - node_js: '5'
      env: TASK=test
    - node_js: '6'
      env: TASK=test

script: "npm run $TASK"

